name: Build & Deploy

on:
  push:
    branches:
      - main
  release:
    tags:
      - v*.*.*
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Build
      run: |
        npm install
        npm run compile

    - name: Publish
      if: github.event_name == 'release'
      run: |
        npm run deploy
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
